
- name: "Install PostgreSQL {{postgresql_version:}}"

#  vars_prompt:
#    selected_hosts: Specify the hosts to provision

# hosts: "{{selected_hosts}}"
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - include: tasks/main.yml
